issue-4195 - Adjust reorder functionality
scandipwa/sales-graphql pull request #12
Opened 2022-03-06 21:23 UTC by AleksandrsKondratjevs

**Fixes**
* scandipwa/scandipwa#4195

**Problems**
* User can't reorder if order was made in other store. On default magento it gets store id from order instead of current store.

**In this PR**
* Adjust reorder functionality

2022-03-24 17:36 UTC, aleksandrsm commented on Model/Resolver/Reorder.php
> +/**
change copyright to PWA's

2022-03-24 17:36 UTC, aleksandrsm commented on Model/Resolver/Reorder.php
> +    public $orderFactory;
assume this will be tagged in latest PWA? then php 7.4 features - public OrderFactory $orderFactory;
same for other props

2022-03-24 17:41 UTC, AleksandrsKondratjevs commented on Model/Resolver/Reorder.php
> +/**
I see we have almost in all files docs from magento instead of our pwa. We need to be consisted. 
Question is: you think we need to rename them all to our doc or stay as magento?

2022-03-24 17:46 UTC, aleksandrsm commented on Model/Resolver/Reorder.php
> +     * @inheritDoc
could use a comment on the purpose of the rewrite
which was to remove the store id filter from the order load

2022-03-24 17:47 UTC, aleksandrsm requested changes
minor code style comments

2022-03-24 18:15 UTC, aleksandrsm commented on Model/Resolver/Reorder.php
> +/**
Agreed on consistency.
And I'd say that we need to rename them all.

2022-03-28 22:24 UTC, aleksandrsm approved these changes

2022-05-13 16:01 UTC, merged